version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: eduforge_v2
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'

  # eduforge:
  #   build: .
  #   ports:
  #     - '3001:3001'
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     DATABASE_URL: postgresql://postgres:123456@postgres:5432/eduforge_v2
  #     JWT_SECRET: change-this-in-production
  #     PORT: 3001

volumes:
  pgdata:
